# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alon Zakai
description: > # this means to ignore newlines until "baseurl:"
  Compiling to the Web, Emscripten, Binaryen, WebAssembly, etc.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://kripken.github.com" # the base hostname & protocol for your site
twitter_username: kripken
github_username:  kripken

# Build settings
markdown: kramdown

theme: "minima"

